# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tasks.protos import permission_pb2 as tasks_dot_protos_dot_permission__pb2


class PermissionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckRole = channel.unary_unary(
                '/permission.Permission/CheckRole',
                request_serializer=tasks_dot_protos_dot_permission__pb2.CheckRoleRequest.SerializeToString,
                response_deserializer=tasks_dot_protos_dot_permission__pb2.CheckRoleResponse.FromString,
                )
        self.CheckUserID = channel.unary_unary(
                '/permission.Permission/CheckUserID',
                request_serializer=tasks_dot_protos_dot_permission__pb2.CheckUserIDRequest.SerializeToString,
                response_deserializer=tasks_dot_protos_dot_permission__pb2.CheckUserIDResponse.FromString,
                )


class PermissionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CheckRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PermissionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckRole': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckRole,
                    request_deserializer=tasks_dot_protos_dot_permission__pb2.CheckRoleRequest.FromString,
                    response_serializer=tasks_dot_protos_dot_permission__pb2.CheckRoleResponse.SerializeToString,
            ),
            'CheckUserID': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserID,
                    request_deserializer=tasks_dot_protos_dot_permission__pb2.CheckUserIDRequest.FromString,
                    response_serializer=tasks_dot_protos_dot_permission__pb2.CheckUserIDResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'permission.Permission', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Permission(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CheckRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/permission.Permission/CheckRole',
            tasks_dot_protos_dot_permission__pb2.CheckRoleRequest.SerializeToString,
            tasks_dot_protos_dot_permission__pb2.CheckRoleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckUserID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/permission.Permission/CheckUserID',
            tasks_dot_protos_dot_permission__pb2.CheckUserIDRequest.SerializeToString,
            tasks_dot_protos_dot_permission__pb2.CheckUserIDResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
