# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks/protos/user.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder


# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17tasks/protos/user.proto\x12\x04user\"!\n\x10UserRequestToken\x12\r\n\x05token\x18\x01 \x01(\t\" \n\rUserRequestID\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"\\\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0c\n\x04role\x18\x05 \x01(\t2\x80\x01\n\x04User\x12>\n\x0e\x43heckUserToken\x12\x16.user.UserRequestToken\x1a\x12.user.UserResponse\"\x00\x12\x38\n\x0b\x43heckUserID\x12\x13.user.UserRequestID\x1a\x12.user.UserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks.protos.user_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERREQUESTTOKEN']._serialized_start=33
  _globals['_USERREQUESTTOKEN']._serialized_end=66
  _globals['_USERREQUESTID']._serialized_start=68
  _globals['_USERREQUESTID']._serialized_end=100
  _globals['_USERRESPONSE']._serialized_start=102
  _globals['_USERRESPONSE']._serialized_end=194
  _globals['_USER']._serialized_start=197
  _globals['_USER']._serialized_end=325
# @@protoc_insertion_point(module_scope)
