# Generated by Django 4.2.6 on 2023-10-21 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=32)),
            ],
            options={
                "verbose_name": "Board",
                "verbose_name_plural": "Boards",
            },
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=32)),
                ("board", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasks.board")),
            ],
            options={
                "verbose_name": "Column",
                "verbose_name_plural": "Columns",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=64)),
                ("executor_id", models.IntegerField(blank=True, null=True)),
                ("column", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tasks.column")),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
