# Generated by Django 4.2.6 on 2023-10-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="owner_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="column",
            name="owner_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="owner_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="owner_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
