# Generated by Django 4.2.6 on 2023-10-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_taskstatus_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="owner_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="owner_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskstatus",
            name="owner_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
