# Generated by Django 4.2.6 on 2023-12-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_board_owner_id_alter_column_owner_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
