# Generated by Django 4.2.6 on 2023-10-21 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_board_owner_id_alter_task_owner_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="board",
            options={"verbose_name": "Board", "verbose_name_plural": "Boards"},
        ),
    ]
