# Generated by Django 4.2.6 on 2024-01-24 15:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_task_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="whitelist",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, null=True, size=None
            ),
        ),
    ]
